---
title: "Bootstrapping procedure for correlation coefficient"
output: html_document
---

```{r echo=FALSE}

cordata <- read.csv("correlation.csv", header=TRUE)
str(cordata)
```

Simple correlation
```{r}

cor.test(cordata[,1], cordata[,2])
```

Correlation with bootstrapping procedure
```{r}

library(boot)

# for reproducibility of bootstrapping results
set.seed = 1333

# boot function requires input of a function created to generate the statistic of interest
# at the very least, need to have two inputs to this created function: dataset and indices
# indices term will later be used by boot function to sample from dataset
runcor <- function(data, indices = c(1:nrow(data))) {
  data2 <- data[indices, ]
  return(cor.test(data2[,1], data2[,2])$estimate)
}

# for boot function, need to specify the "data" parameter, the above created function as the input to the "statistic" parameter, and the number of times to repeat the bootstrapping procedure
bootresults <- boot(data = cordata, 
                    statistic = runcor, 
                    R = 1000)
# view results
bootresults

# calculate confidence intervals
boot.ci(bootresults, conf = .95)

# view distribution of bootstrapped correlation coefficients
hist(bootresults$t, breaks = 20, xlim=c(-1, 1), 
     main = "Bootstrapped correlation coefficients", xlab = "Pearson's r")

```

**Conclusion**
  
A non-parametric bootstrapping procedure with 1000 replicates (using the *boot* library in R, version 1.3-25; Davison & Hinkley, 1997) showed that the 95% confidence interval for the correlation coefficient of -0.4765 was (-0.7754, -0.1976; using a normal approximation).
